# Generated by Django 4.0.4 on 2022-04-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuerpotecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(max_length=40)),
                ('funcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(max_length=40)),
                ('posicion', models.CharField(max_length=40)),
                ('dorsalcamiseta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='juntadirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreapellido', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
